# Generated by Django 5.2.8 on 2025-12-02 14:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Landmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('location', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('museum', 'Museum'), ('monument', 'Monument'), ('park', 'Park'), ('historical', 'Historical Site'), ('other', 'Other')], default='other', max_length=20)),
                ('opening_hours', models.CharField(blank=True, max_length=100, null=True)),
                ('entry_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('schedule', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ManyToManyField(blank=True, null=True, related_name='user_bus', to=settings.AUTH_USER_MODEL)),
                ('landmarks', models.ManyToManyField(related_name='buses', to='tajikistan.landmark')),
            ],
        ),
    ]
